[package]
name = "bitcoinz"
version = "0.1.0"
edition = "2021"
description = "Rust implementation of BitcoinZ"
authors = ["Your Name <you@example.com>"]
license = "MIT"
repository = "https://github.com/btcz/bitcoinz"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
bincode = "1.3"
sha2 = "0.10"
clap = { version = "4.0", features = ["derive"] }
crc32fast = "1.3"
sled = "0.34"
serde_json = "1.0"
num-bigint = "0.4"
num-traits = "0.2"
base58 = "0.2"
bech32 = "0.9"
bitcoin = "0.30"
bloom = "0.7"
log = "0.4"
ripemd160 = "0.10"
hex = "0.4"
secp256k1 = "0.23"
rand = "0.8"
fern = "0.6"
chrono = "0.4"
warp = "0.3"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
[features]
default = ["cli", "node"]

[build-dependencies]
cc = "1.0"

[bin]
name = "bitcoinz-cli"
path = "src/bin/bitcoinz_cli.rs"

[[bin]]
name = "bitcoind"
path = "src/bin/bitcoind.rs"

[lib]
name = "bitcoinz"
path = "src/lib.rs"

[profile.release]
opt-level = 3
debug = true
